// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEo3OnoKDpsFTWEwQVIunDrTJf1zv7pqA',
    appId: '1:243608624557:web:c38c6217326bb5f437d524',
    messagingSenderId: '243608624557',
    projectId: 'pulsepledge-83118',
    authDomain: 'pulsepledge-83118.firebaseapp.com',
    storageBucket: 'pulsepledge-83118.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCcIPElVYakc7WRXvvwM4agjPK5va3-Ek',
    appId: '1:243608624557:android:8afdbffef5483c1637d524',
    messagingSenderId: '243608624557',
    projectId: 'pulsepledge-83118',
    storageBucket: 'pulsepledge-83118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGYQSOQamW0r2ivsz7E6y38eIulNal_dU',
    appId: '1:243608624557:ios:60962cca6496b65237d524',
    messagingSenderId: '243608624557',
    projectId: 'pulsepledge-83118',
    storageBucket: 'pulsepledge-83118.appspot.com',
    iosBundleId: 'com.example.donorCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGYQSOQamW0r2ivsz7E6y38eIulNal_dU',
    appId: '1:243608624557:ios:be121332e17927a737d524',
    messagingSenderId: '243608624557',
    projectId: 'pulsepledge-83118',
    storageBucket: 'pulsepledge-83118.appspot.com',
    iosBundleId: 'com.example.donorCommunity.RunnerTests',
  );
}
